name: build website

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  b1:
    name: build website
    runs-on: ubuntu-22.04
    env:
      MY_YARN_CACHE_DIR: .yarn/cache
      CI: true
    steps:
      - name: checkout sources
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
      - name: uninstall old angular cli
        run: npm uninstall -g @angular/cli
      - name: install latest angular cli
        run: npm install -g @angular/cli@latest
      - name: configure angular to use yarn
        run: ng config -g cli.packageManager yarn
      - name: print versions
        run: |
          echo "NPM: $(npm -v)"
          echo "Node: $(node -v)"
          echo "Yarn: $(yarn -v)"
          echo "NG: $(ng version)"
      - name: install packages
        run: yarn --immutable
      - name: build it with ng
        run: PATH=$(pwd)/node_modules/.bin:$PATH ng build
